// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/clearthree/url-shortener/internal/app/service (interfaces: ShortURLServiceInterface)

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockShortURLServiceInterface is a mock of ShortURLServiceInterface interface.
type MockShortURLServiceInterface struct {
	ctrl     *gomock.Controller
	recorder *MockShortURLServiceInterfaceMockRecorder
}

// MockShortURLServiceInterfaceMockRecorder is the mock recorder for MockShortURLServiceInterface.
type MockShortURLServiceInterfaceMockRecorder struct {
	mock *MockShortURLServiceInterface
}

// NewMockShortURLServiceInterface creates a new mock instance.
func NewMockShortURLServiceInterface(ctrl *gomock.Controller) *MockShortURLServiceInterface {
	mock := &MockShortURLServiceInterface{ctrl: ctrl}
	mock.recorder = &MockShortURLServiceInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockShortURLServiceInterface) EXPECT() *MockShortURLServiceInterfaceMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockShortURLServiceInterface) Create(arg0 string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", arg0)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockShortURLServiceInterfaceMockRecorder) Create(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockShortURLServiceInterface)(nil).Create), arg0)
}

// Ping mocks base method.
func (m *MockShortURLServiceInterface) Ping() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Ping")
	ret0, _ := ret[0].(error)
	return ret0
}

// Ping indicates an expected call of Ping.
func (mr *MockShortURLServiceInterfaceMockRecorder) Ping() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Ping", reflect.TypeOf((*MockShortURLServiceInterface)(nil).Ping))
}

// Read mocks base method.
func (m *MockShortURLServiceInterface) Read(arg0 string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Read", arg0)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Read indicates an expected call of Read.
func (mr *MockShortURLServiceInterfaceMockRecorder) Read(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Read", reflect.TypeOf((*MockShortURLServiceInterface)(nil).Read), arg0)
}
